<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Material;
use App\Models\Question;
use App\Models\QuestionCategory;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        $material = Material::create([
            'user_id' => 1,
            'parent_id' => null,
            'type' => 'book',
            'name' => '2024년 12월 3일 수학 문제집',
            'image_path' => null,
            'is_public' => true,
        ]);

        $questions = [
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_1.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 231, "y": 790, "width": 974, "height": 284, "pageNumber": 1, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                'material_id' => $material->id,
                'seq' => 1,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_2.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 238, "y": 1814, "width": 950, "height": 412, "pageNumber": 1, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                'material_id' => $material->id,
                'seq' => 2,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_3.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 1276, "y": 635, "width": 980, "height": 238, "pageNumber": 1, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                'material_id' => $material->id,
                'seq' => 3,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_4.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 1288, "y": 1853, "width": 949, "height": 284, "pageNumber": 1, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                'material_id' => $material->id,
                'seq' => 4,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_5.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 238, "y": 358, "width": 951, "height": 222, "pageNumber": 2, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                'material_id' => $material->id,
                'seq' => 5,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_6.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 238, "y": 1745, "width": 952, "height": 223, "pageNumber": 2, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                // 'material_id' => $material->id,
                // 'seq' => 6,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 18,
                'parent_question_id' => null,
                'question_display_type' => 'image',
                'content' => null,
                'image_path' => '/converted-pdfs/01JE5JGSYVGVPAR6A7X97E7CSA/questions/question_7.jpg',
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'content',
                'choices_display_type' => 'in_question',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => null,
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => '{"x": 1289, "y": 358, "width": 951, "height": 374, "pageNumber": 2, "sourceWidth": 2479, "sourceHeight": 3504}',
                'created_at' => '2024-12-03 15:20:22',
                'updated_at' => '2024-12-03 15:20:22',
                'deleted_at' => null,
                // 'material_id' => $material->id,
                // 'seq' => 7,
            ],
            [
                'user_id' => 1,
                'question_type_id' => 19,
                'parent_question_id' => null,
                'question_display_type' => 'content',
                'content' => '<p><math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced><mrow><msqrt><mn>3</mn></msqrt><mo>-</mo><msup><mn>1</mn><mn>3</mn></msup></mrow></mfenced><mo>÷</mo><msqrt><mn>2</mn></msqrt></math>의 값은?</p>',
                'image_path' => null,
                'level' => 1,
                'answer_type' => 'multiple_choice',
                'answer' => 1,
                'explanation_display_type' => 'image',
                'choices_display_type' => 'seperate',
                'explanation' => '<p>1</p>',
                'explanation_image_path' => '01JE7VJS3ATE2BZKNT6DJA4SYG.png',
                'explanation_video_url' => null,
                'tags' => '""',
                'metadata' => null,
                'created_at' => '2024-12-04 10:30:03',
                'updated_at' => '2024-12-04 12:31:52',
                'deleted_at' => null,
                'material_id' => $material->id,
                'seq' => 6,
            ],
        ];

        foreach ($questions as $question) {
            DB::table('questions')->insert($question);
        }
    }
}
